## 변수정의

In [17]:
a = 1; print(type(a))

<class 'int'>


Python에서의 = 기호는 수학적 의미의 같다를 의미하지 않는다. =를 기준으로 왼쪽은 variable, 오른쪽은 content를 의미한다. variables만 적으면 마지막에 적은 것의 content만 print된다. a = 1, b = 2 모두를 나오게 할 땐 print(a), print(b)라고 표기하면 된다.
print(type(a))의 아웃풋인 int는 integer를 의미하며, 이는 a의 클래스이다. 각각의 variables는 정하기 나름인 type을 가지고 있다.

In [1]:
a = 1; a = float(a); print(type(a))

<class 'float'>


소수점이 있는 숫자를 float라고 한다.float를 int로, int를 float로 바꿀 수 있다. 예를 들어, a = 1.0일 때 이 a를 다시 int로 바꾸려면 int(a)하면 된다.

In [19]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


a = 1.2인 상태에서 int(a)를 하면 1이 나오는데 이는 a 자체가 바뀐 게 아니라 그냥 int로 바꿔서 보여주는 것이다.

In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


str는 string의 약자로, 문자를 의미한다.
print(a[1])을 했을 때 1이 아니라 2가 나오는 이유는, python에서는 첫번째가 n = 0이기 때문이다.1은 두번째 문자를 의미하기 때문에 2가 나오는 것이다.
이 때, a = [-1]을 하면 맨 끝 문자가 나온다. 이는 아주 긴 string에서 맨 끝 문자만을 보고 싶을 때 유용하게 사용된다.

In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


대괄호가 있고, 각 문자가 콤마로 구분되어 있으면 list이다. 위는 string을 list로 바꾼 모습이다. 그리고 앞선 경우와 마찬가지로 2를 입력하면 세번째 문자인 3이 나온다.

In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


tuple은 list와 동일하다고 보면 된다.

In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


dict는 dictionary의 약자이다. a에 담겨 있는 의미를 보여준다. "a"가 표제어이고, "apple"은 그에 해당하는 설명(content)이다. 즉 이 경우는 숫자가 아니라 표제어로 접근한 모습이다.

In [2]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

타입은 리스트. 리스트 안 내용은 두 개. 리스트와 비슷하게 생겼지만 튜플. 같다고 생각하면 됨. 리스트 안에 튜플로 들어간 형태. 행렬과 비슷. 2x3 행렬. (3, 8, 0)이 (1, 2, 3) 밑으로.

In [3]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


import numpy as np: 폴더 수가 많아서 줄여 쓰고 싶을 때 이렇게 한다. 27의 아웃풋이 튜플이 두 개 들어 있는 리스트였으므로, 이 아웃풋의 결과는 보다 더 행렬과 같아지게 변하여 나오게 된다.

In [29]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


만약 위에서의 아웃풋이 실제 행렬이었다면 이 곱셈은 성립이 될 수 없다. 2x3 행렬 두 개를 곱할 수는 없기 때문이다. 즉 이 아웃풋이 실제 행렬은 아니라는 것을 알 수 있다. 곱의 결과는 같은 자리에 있는 element끼리의 곱이다.

In [30]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


c는 실제 행렬(matrix)이다. c = np.matrix(b)는 c를 실제 행렬로 만들었음을 보여준다.

In [31]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

위에서 c가 실제 행렬이기 때문에 곱셈이 성립되지 않는 것이다. ValueError에서도 행렬의 모양때문에 곱셈이 성립할 수 없음을 설명하고 있다.

In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])

c를 transpose하게 해주는 것이 .T의 역할이다. 2x3 행렬 하나를 3x2로 만들어 곱이 가능하게 하는 것이다.